/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.hook.calendar.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.hook.calendar.model.CalEventAttendee;
import com.liferay.hook.calendar.service.CalEventAttendeeLocalService;
import com.liferay.hook.calendar.service.CalEventAttendeeService;
import com.liferay.hook.calendar.service.persistence.CalEventAttendeePersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the cal event attendee local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.hook.calendar.service.impl.CalEventAttendeeLocalServiceImpl}.
 * </p>
 *
 * @author Joaquin Cabal
 * @see com.liferay.hook.calendar.service.impl.CalEventAttendeeLocalServiceImpl
 * @see com.liferay.hook.calendar.service.CalEventAttendeeLocalServiceUtil
 * @generated
 */
public abstract class CalEventAttendeeLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements CalEventAttendeeLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.hook.calendar.service.CalEventAttendeeLocalServiceUtil} to access the cal event attendee local service.
	 */

	/**
	 * Adds the cal event attendee to the database. Also notifies the appropriate model listeners.
	 *
	 * @param calEventAttendee the cal event attendee
	 * @return the cal event attendee that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public CalEventAttendee addCalEventAttendee(
		CalEventAttendee calEventAttendee) throws SystemException {
		calEventAttendee.setNew(true);

		return calEventAttendeePersistence.update(calEventAttendee, false);
	}

	/**
	 * Creates a new cal event attendee with the primary key. Does not add the cal event attendee to the database.
	 *
	 * @param calEventAttendeeId the primary key for the new cal event attendee
	 * @return the new cal event attendee
	 */
	public CalEventAttendee createCalEventAttendee(long calEventAttendeeId) {
		return calEventAttendeePersistence.create(calEventAttendeeId);
	}

	/**
	 * Deletes the cal event attendee with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param calEventAttendeeId the primary key of the cal event attendee
	 * @return the cal event attendee that was removed
	 * @throws PortalException if a cal event attendee with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public CalEventAttendee deleteCalEventAttendee(long calEventAttendeeId)
		throws PortalException, SystemException {
		return calEventAttendeePersistence.remove(calEventAttendeeId);
	}

	/**
	 * Deletes the cal event attendee from the database. Also notifies the appropriate model listeners.
	 *
	 * @param calEventAttendee the cal event attendee
	 * @return the cal event attendee that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public CalEventAttendee deleteCalEventAttendee(
		CalEventAttendee calEventAttendee) throws SystemException {
		return calEventAttendeePersistence.remove(calEventAttendee);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(CalEventAttendee.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return calEventAttendeePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return calEventAttendeePersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return calEventAttendeePersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return calEventAttendeePersistence.countWithDynamicQuery(dynamicQuery);
	}

	public CalEventAttendee fetchCalEventAttendee(long calEventAttendeeId)
		throws SystemException {
		return calEventAttendeePersistence.fetchByPrimaryKey(calEventAttendeeId);
	}

	/**
	 * Returns the cal event attendee with the primary key.
	 *
	 * @param calEventAttendeeId the primary key of the cal event attendee
	 * @return the cal event attendee
	 * @throws PortalException if a cal event attendee with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public CalEventAttendee getCalEventAttendee(long calEventAttendeeId)
		throws PortalException, SystemException {
		return calEventAttendeePersistence.findByPrimaryKey(calEventAttendeeId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return calEventAttendeePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the cal event attendees.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of cal event attendees
	 * @param end the upper bound of the range of cal event attendees (not inclusive)
	 * @return the range of cal event attendees
	 * @throws SystemException if a system exception occurred
	 */
	public List<CalEventAttendee> getCalEventAttendees(int start, int end)
		throws SystemException {
		return calEventAttendeePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of cal event attendees.
	 *
	 * @return the number of cal event attendees
	 * @throws SystemException if a system exception occurred
	 */
	public int getCalEventAttendeesCount() throws SystemException {
		return calEventAttendeePersistence.countAll();
	}

	/**
	 * Updates the cal event attendee in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param calEventAttendee the cal event attendee
	 * @return the cal event attendee that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public CalEventAttendee updateCalEventAttendee(
		CalEventAttendee calEventAttendee) throws SystemException {
		return updateCalEventAttendee(calEventAttendee, true);
	}

	/**
	 * Updates the cal event attendee in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param calEventAttendee the cal event attendee
	 * @param merge whether to merge the cal event attendee with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the cal event attendee that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public CalEventAttendee updateCalEventAttendee(
		CalEventAttendee calEventAttendee, boolean merge)
		throws SystemException {
		calEventAttendee.setNew(false);

		return calEventAttendeePersistence.update(calEventAttendee, merge);
	}

	/**
	 * Returns the cal event attendee local service.
	 *
	 * @return the cal event attendee local service
	 */
	public CalEventAttendeeLocalService getCalEventAttendeeLocalService() {
		return calEventAttendeeLocalService;
	}

	/**
	 * Sets the cal event attendee local service.
	 *
	 * @param calEventAttendeeLocalService the cal event attendee local service
	 */
	public void setCalEventAttendeeLocalService(
		CalEventAttendeeLocalService calEventAttendeeLocalService) {
		this.calEventAttendeeLocalService = calEventAttendeeLocalService;
	}

	/**
	 * Returns the cal event attendee remote service.
	 *
	 * @return the cal event attendee remote service
	 */
	public CalEventAttendeeService getCalEventAttendeeService() {
		return calEventAttendeeService;
	}

	/**
	 * Sets the cal event attendee remote service.
	 *
	 * @param calEventAttendeeService the cal event attendee remote service
	 */
	public void setCalEventAttendeeService(
		CalEventAttendeeService calEventAttendeeService) {
		this.calEventAttendeeService = calEventAttendeeService;
	}

	/**
	 * Returns the cal event attendee persistence.
	 *
	 * @return the cal event attendee persistence
	 */
	public CalEventAttendeePersistence getCalEventAttendeePersistence() {
		return calEventAttendeePersistence;
	}

	/**
	 * Sets the cal event attendee persistence.
	 *
	 * @param calEventAttendeePersistence the cal event attendee persistence
	 */
	public void setCalEventAttendeePersistence(
		CalEventAttendeePersistence calEventAttendeePersistence) {
		this.calEventAttendeePersistence = calEventAttendeePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.liferay.hook.calendar.model.CalEventAttendee",
			calEventAttendeeLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.liferay.hook.calendar.model.CalEventAttendee");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return CalEventAttendee.class;
	}

	protected String getModelClassName() {
		return CalEventAttendee.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = calEventAttendeePersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = CalEventAttendeeLocalService.class)
	protected CalEventAttendeeLocalService calEventAttendeeLocalService;
	@BeanReference(type = CalEventAttendeeService.class)
	protected CalEventAttendeeService calEventAttendeeService;
	@BeanReference(type = CalEventAttendeePersistence.class)
	protected CalEventAttendeePersistence calEventAttendeePersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private CalEventAttendeeLocalServiceClpInvoker _clpInvoker = new CalEventAttendeeLocalServiceClpInvoker();
}