/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.hook.calendar.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the CalEventAttendee service. Represents a row in the &quot;cal_CalEventAttendee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.hook.calendar.model.impl.CalEventAttendeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.hook.calendar.model.impl.CalEventAttendeeImpl}.
 * </p>
 *
 * @author Joaquin Cabal
 * @see CalEventAttendee
 * @see com.liferay.hook.calendar.model.impl.CalEventAttendeeImpl
 * @see com.liferay.hook.calendar.model.impl.CalEventAttendeeModelImpl
 * @generated
 */
public interface CalEventAttendeeModel extends BaseModel<CalEventAttendee> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cal event attendee model instance should use the {@link CalEventAttendee} interface instead.
	 */

	/**
	 * Returns the primary key of this cal event attendee.
	 *
	 * @return the primary key of this cal event attendee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cal event attendee.
	 *
	 * @param primaryKey the primary key of this cal event attendee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cal event attendee ID of this cal event attendee.
	 *
	 * @return the cal event attendee ID of this cal event attendee
	 */
	public long getCalEventAttendeeId();

	/**
	 * Sets the cal event attendee ID of this cal event attendee.
	 *
	 * @param calEventAttendeeId the cal event attendee ID of this cal event attendee
	 */
	public void setCalEventAttendeeId(long calEventAttendeeId);

	/**
	 * Returns the event ID of this cal event attendee.
	 *
	 * @return the event ID of this cal event attendee
	 */
	public long getEventId();

	/**
	 * Sets the event ID of this cal event attendee.
	 *
	 * @param eventId the event ID of this cal event attendee
	 */
	public void setEventId(long eventId);

	/**
	 * Returns the user ID of this cal event attendee.
	 *
	 * @return the user ID of this cal event attendee
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this cal event attendee.
	 *
	 * @param userId the user ID of this cal event attendee
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this cal event attendee.
	 *
	 * @return the user uuid of this cal event attendee
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this cal event attendee.
	 *
	 * @param userUuid the user uuid of this cal event attendee
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the assist of this cal event attendee.
	 *
	 * @return the assist of this cal event attendee
	 */
	public boolean getAssist();

	/**
	 * Returns <code>true</code> if this cal event attendee is assist.
	 *
	 * @return <code>true</code> if this cal event attendee is assist; <code>false</code> otherwise
	 */
	public boolean isAssist();

	/**
	 * Sets whether this cal event attendee is assist.
	 *
	 * @param assist the assist of this cal event attendee
	 */
	public void setAssist(boolean assist);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(CalEventAttendee calEventAttendee);

	public int hashCode();

	public CacheModel<CalEventAttendee> toCacheModel();

	public CalEventAttendee toEscapedModel();

	public String toString();

	public String toXmlString();
}